### ISSUE TITLE
Erro!

### ISSUE THREAD

**Issue by DeLuca92** [bernardotonin/real-state-scraper#2]
Estou tentando usar o projeto estou com alguns erros :/

Deu quase tudo certo MAS

no npm start da o seguinte erro

```
pm start 
npm ERR! Missing script: "start"
npm ERR! 
npm ERR! Did you mean one of these?
npm ERR!     npm star # Mark your favorite packages
npm ERR!     npm stars # View packages marked as favorites
npm ERR! 
npm ERR! To see a list of scripts, run:
npm ERR!   npm run

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/daniel/.npm/_logs/2024-11-01T21_27_23_202Z-debug-0.log
```

Dai coloquei npm run dev

```
> scrapper@1.0.0 dev
> tsx watch src/

node:internal/errors:496
    ErrorCaptureStackTrace(err);
    ^

TypeError [ERR_INVALID_URL]: Invalid URL
    at __node_internal_captureLargerStackTrace (node:internal/errors:496:5)
    at new NodeError (node:internal/errors:405:5)
    at new URL (node:internal/url:676:13)
    at HttpsProxyAgent (/home/daniel/Desktop/zapimoveis/real-state-scraper/node_modules/https-proxy-agent/src/index.ts:54:44)
    at <anonymous> (/home/daniel/Desktop/zapimoveis/real-state-scraper/src/lib/constants.ts:11:27)
    at ModuleJob.run (node:internal/modules/esm/module_job:195:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:336:24)
    at async loadESM (node:internal/process/esm_loader:34:7)
    at async handleMainPromise (node:internal/modules/run_main:106:12) {
  input: '',
  code: 'ERR_INVALID_URL'
}

Node.js v18.19.1

```
Saberia me ajudar?

**Comment by bernardotonin** [comment]
Boa noite, DeLuca92!

O readme está errado, o comando para rodar é de fato o `npm run dev`, peço desculpas por isso.

Quanto ao segundo erro, ele refere-se ao endereço proxy. Essa aplicação foi desenvolvida em um ambiente corporativo, onde se fazia necessário a autenticação via proxy. Para rodar a aplicação sem proxy, faça as seguintes alterações:

**src/scraper/zap.ts**

```const fetchFromZap = async (
  from: number,
  size: number
): Promise<PrismaProperty[]> => {
  const response = await fetch(getZapUrl(from, size), {
    agent: ProxyAgent, // <-- remover essa linha.
    headers: ZapHeaders,
  });
  const json = await response.json() as ZapJSON;
  return parseJson(json.search.result.listings);
};

export const getZapCount = async (): Promise<number> => {
  const response = await fetch(getZapUrl(0, 3), {
    agent: ProxyAgent, // <-- remover essa linha
    headers: ZapHeaders,
  });
  const json = await response.json() as ZapJSON;
  return Math.floor(json.search.totalCount / 108);
};
```
**src/scraper/viva.ts**

```export const getVivaCount = async (): Promise<number> => {
  const response = await fetch(getVivaUrl(0, 0), {
    agent: ProxyAgent, // <-- remover essa linha
    headers: VivaHeaders,
  });
  const json = await response.json() as ZapJSON;
  return Math.floor(json.search.totalCount / 108);
};

export const fetchFromViva = async (
  from: number,
  size: number
): Promise<PrismaProperty[]> => {
  const response = await fetch(getVivaUrl(from, size), {
    agent: ProxyAgent,  // <-- remover essa linha
    headers: VivaHeaders,
  });
  const json = await response.json() as ZapJSON;
  return parseJson(json.search.result.listings);
};
```

Peço desculpas por não elaborar o uso do proxy no readme, irei atualizar assim que possivel.

Caso tenha qualquer outro erro, ficarei feliz em ajudar-lo.

Atenciosamente, Bernardo Tonin.

**Comment by DeLuca92** [comment]
Bom Dia,

Fiz os ajustes, tbm tirei o  ProxyAgent do constants.ts

Rodai o comando npx prisma generate

dai rodei o npm run dev
```
> scrapper@1.0.0 dev
> tsx watch src/

undefined:1
<!DOCTYPE html>
^

SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at Response.json (/home/daniel/Desktop/zapimoveis/real-state-scraper/node_modules/node-fetch/src/body.js:149:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at getZapCount (/home/daniel/Desktop/zapimoveis/real-state-scraper/src/scraper/zap.ts:23:16)
    at ZapScrape (/home/daniel/Desktop/zapimoveis/real-state-scraper/src/scraper/zap.ts:30:24)
    at populateDb (/home/daniel/Desktop/zapimoveis/real-state-scraper/src/lib/utils.ts:111:3)

Node.js v18.19.1

```

Casso eu cole a url

```
do codigo lá retorna esse erro

// 20241102151725
// https://glue-api.zapimoveis.com.br/v2/listings?user=e75cb044-fd8e-41a6-a234-50b267383759&portal=ZAP&includeFields=search%28result%28listings%28listing%28contractType%2ClistingsCount%2CsourceId%2CdisplayAddressType%2Camenities%2CusableAreas%2CconstructionStatus%2ClistingType%2Cdescription%2Ctitle%2Cstamps%2CcreatedAt%2Cfloors%2CunitTypes%2CnonActivationReason%2CproviderId%2CpropertyType%2CunitSubTypes%2CunitsOnTheFloor%2ClegacyId%2Cid%2Cportal%2CunitFloor%2CparkingSpaces%2CupdatedAt%2Caddress%2Csuites%2CpublicationType%2CexternalId%2Cbathrooms%2CusageTypes%2CtotalAreas%2CadvertiserId%2CadvertiserContact%2CwhatsappNumber%2Cbedrooms%2CacceptExchange%2CpricingInfos%2CshowPrice%2Cresale%2Cbuildings%2CcapacityLimit%2Cstatus%2CpriceSuggestion%29%2Caccount%28id%2Cname%2ClogoUrl%2ClicenseNumber%2CshowAddress%2ClegacyVivarealId%2ClegacyZapId%2CcreatedDate%2Ctier%29%2Cmedias%2CaccountLink%2Clink%29%29%2CtotalCount%29%2Cpage%2Cfacets%2CfullUriFragments%2Cdevelopments%28search%28result%28listings%28listing%28contractType%2ClistingsCount%2CsourceId%2CdisplayAddressType%2Camenities%2CusableAreas%2CconstructionStatus%2ClistingType%2Cdescription%2Ctitle%2Cstamps%2CcreatedAt%2Cfloors%2CunitTypes%2CnonActivationReason%2CproviderId%2CpropertyType%2CunitSubTypes%2CunitsOnTheFloor%2ClegacyId%2Cid%2Cportal%2CunitFloor%2CparkingSpaces%2CupdatedAt%2Caddress%2Csuites%2CpublicationType%2CexternalId%2Cbathrooms%2CusageTypes%2CtotalAreas%2CadvertiserId%2CadvertiserContact%2CwhatsappNumber%2Cbedrooms%2CacceptExchange%2CpricingInfos%2CshowPrice%2Cresale%2Cbuildings%2CcapacityLimit%2Cstatus%2CpriceSuggestion%29%2Caccount%28id%2Cname%2ClogoUrl%2ClicenseNumber%2CshowAddress%2ClegacyVivarealId%2ClegacyZapId%2CcreatedDate%2Ctier%29%2Cmedias%2CaccountLink%2Clink%29%29%2CtotalCount%29%29%2CsuperPremium%28search%28result%28listings%28listing%28contractType%2ClistingsCount%2CsourceId%2CdisplayAddressType%2Camenities%2CusableAreas%2CconstructionStatus%2ClistingType%2Cdescription%2Ctitle%2Cstamps%2CcreatedAt%2Cfloors%2CunitTypes%2CnonActivationReason%2CproviderId%2CpropertyType%2CunitSubTypes%2CunitsOnTheFloor%2ClegacyId%2Cid%2Cportal%2CunitFloor%2CparkingSpaces%2CupdatedAt%2Caddress%2Csuites%2CpublicationType%2CexternalId%2Cbathrooms%2CusageTypes%2CtotalAreas%2CadvertiserId%2CadvertiserContact%2CwhatsappNumber%2Cbedrooms%2CacceptExchange%2CpricingInfos%2CshowPrice%2Cresale%2Cbuildings%2CcapacityLimit%2Cstatus%2CpriceSuggestion%29%2Caccount%28id%2Cname%2ClogoUrl%2ClicenseNumber%2CshowAddress%2ClegacyVivarealId%2ClegacyZapId%2CcreatedDate%2Ctier%29%2Cmedias%2CaccountLink%2Clink%29%29%2CtotalCount%29%29%2Cschema%2CtopoFixo%28search%28result%28listings%28listing%28listingsCount%2CsourceId%2CdisplayAddressType%2Camenities%2CusableAreas%2CconstructionStatus%2ClistingType%2Cdescription%2Ctitle%2Cstamps%2CcreatedAt%2Cfloors%2CunitTypes%2CnonActivationReason%2CproviderId%2CpropertyType%2CunitSubTypes%2CunitsOnTheFloor%2ClegacyId%2Cid%2Cportal%2CunitFloor%2CparkingSpaces%2CupdatedAt%2Caddress%2Csuites%2CpublicationType%2CexternalId%2Cbathrooms%2CusageTypes%2CtotalAreas%2CadvertiserId%2CadvertiserContact%2CwhatsappNumber%2Cbedrooms%2CacceptExchange%2CpricingInfos%2CshowPrice%2Cresale%2Cbuildings%2CcapacityLimit%2Cstatus%2CpriceSuggestion%2CadvertiserUrl%29%2Caccount%28id%2Cname%2ClogoUrl%2ClicenseNumber%2CshowAddress%2ClegacyVivarealId%2ClegacyZapId%2CcreatedDate%2Ctier%2Crating%29%2Cmedias%2CaccountLink%2Clink%29%29%2CtotalCount%29%29&categoryPage=RESULT&developmentsSize=3&superPremiumSize=3&topoFixoSize=0&business=SALE&parentId=null&listingType=USED&addressCity=Foz+do+Igua%C3%A7u&addressLocationId=BR%3EParana%3ENULL%3EFoz+do+Iguacu&addressState=Paran%C3%A1&addressPointLat=-25.516336&addressPointLon=-54.585376&addressType=city&page=1&size=3&from=0&levels=CITY&ref=&__zt=mtc%3Adeduplication2023&images=webp&viewport=

{
  "err": "{\n  code: 'MISSING-DOMAIN-HEADER',\n  statusCode: 400,\n  details: { message: 'x-domain not set for /v2/listings' }\n}"
}

```

Coloquei um console.log( no zap.ts)
na linha
´´´
export const getZapCount = async (): Promise<number> => {
  const response = await fetch(getZapUrl(0, 3), {
    headers: ZapHeaders
  });
  console.log(response); <--- AQUI
  const json = await response.json() as ZapJSON;
  
  return Math.floor(json.search.totalCount / 108);
};
´´´


Peguei tbm uma url da pesquisa q eu fiz e tive esse retorno aqui


```

// 20241102152034
// https://glue-api.zapimoveis.com.br/v2/listings?user=7710f4f7-b85c-424d-b108-ce7ab1370aed&portal=ZAP&includeFields=page%28link%28href%29%29&categoryPage=RESULT&business=SALE&parentId=null&listingType=USED&addressCity=Porto+Alegre&addressLocationId=BR%3ERio+Grande+do+Sul%3ENULL%3EPorto+Alegre&addressState=Rio+Grande+do+Sul&addressPointLat=-30.036818&addressPointLon=-51.208989&addressType=city&levels=CITY

{
  "err": "{\n  code: 'MISSING-DOMAIN-HEADER',\n  statusCode: 400,\n  details: { message: 'x-domain not set for /v2/listings' }\n}"
}
````



Talvez agora tenha q enviar esse DOMAIN-HEADE junto

Na realidade o problema é na hora de montar o json, que ele se perde. :/
